<h1>100道练习带你玩转Numpy<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#导入numpy库简写为np" data-toc-modified-id="导入numpy库简写为np-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>导入numpy库简写为np</a></span></li><li><span><a href="#打印numpy的版本和配置说明" data-toc-modified-id="打印numpy的版本和配置说明-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>打印numpy的版本和配置说明</a></span></li><li><span><a href="#创建一个长度为10的空向量" data-toc-modified-id="创建一个长度为10的空向量-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>创建一个长度为10的空向量</a></span></li><li><span><a href="#如何找到任何一个数组的内存大小？" data-toc-modified-id="如何找到任何一个数组的内存大小？-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>如何找到任何一个数组的内存大小？</a></span></li><li><span><a href="#如何从命令行得到numpy中add函数的说明文档?" data-toc-modified-id="如何从命令行得到numpy中add函数的说明文档?-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>如何从命令行得到numpy中add函数的说明文档?</a></span></li><li><span><a href="#创建一个长度为10并且除了第五个值为1的空向量" data-toc-modified-id="创建一个长度为10并且除了第五个值为1的空向量-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>创建一个长度为10并且除了第五个值为1的空向量</a></span></li><li><span><a href="#创建一个值域范围从10到49的向量" data-toc-modified-id="创建一个值域范围从10到49的向量-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>创建一个值域范围从10到49的向量</a></span></li><li><span><a href="#反转一个向量(第一个元素变为最后一个)" data-toc-modified-id="反转一个向量(第一个元素变为最后一个)-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>反转一个向量(第一个元素变为最后一个)</a></span></li><li><span><a href="#创建一个-3x3-并且值从0到8的矩阵" data-toc-modified-id="创建一个-3x3-并且值从0到8的矩阵-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>创建一个 3x3 并且值从0到8的矩阵</a></span></li><li><span><a href="#找到数组[1,2,0,0,4,0]中非0元素的位置索引" data-toc-modified-id="找到数组[1,2,0,0,4,0]中非0元素的位置索引-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>找到数组[1,2,0,0,4,0]中非0元素的位置索引</a></span></li><li><span><a href="#创建一个-3x3-的单位矩阵" data-toc-modified-id="创建一个-3x3-的单位矩阵-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>创建一个 3x3 的单位矩阵</a></span></li><li><span><a href="#创建一个-3x3x3的随机数组" data-toc-modified-id="创建一个-3x3x3的随机数组-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>创建一个 3x3x3的随机数组</a></span></li><li><span><a href="#创建一个-10x10-的随机数组并找到它的最大值和最小值" data-toc-modified-id="创建一个-10x10-的随机数组并找到它的最大值和最小值-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>创建一个 10x10 的随机数组并找到它的最大值和最小值</a></span></li><li><span><a href="#创建一个长度为30的随机向量并找到它的平均值" data-toc-modified-id="创建一个长度为30的随机向量并找到它的平均值-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>创建一个长度为30的随机向量并找到它的平均值</a></span></li><li><span><a href="#创建一二维数组，其中边界值为1，其余值为0" data-toc-modified-id="创建一二维数组，其中边界值为1，其余值为0-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>创建一二维数组，其中边界值为1，其余值为0</a></span></li><li><span><a href="#对于一个存在在数组，如何添加一个用0填充的边界?" data-toc-modified-id="对于一个存在在数组，如何添加一个用0填充的边界?-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>对于一个存在在数组，如何添加一个用0填充的边界?</a></span></li><li><span><a href="#以下表达式运行的结果分别是什么?" data-toc-modified-id="以下表达式运行的结果分别是什么?-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>以下表达式运行的结果分别是什么?</a></span></li><li><span><a href="#创建一个-5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置" data-toc-modified-id="创建一个-5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置</a></span></li><li><span><a href="#创建一个8x8-的矩阵，并且设置成棋盘样式" data-toc-modified-id="创建一个8x8-的矩阵，并且设置成棋盘样式-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>创建一个8x8 的矩阵，并且设置成棋盘样式</a></span></li><li><span><a href="#考虑一个-(6,7,8)-形状的数组，其第100个元素的索引(x,y,z)是什么?" data-toc-modified-id="考虑一个-(6,7,8)-形状的数组，其第100个元素的索引(x,y,z)是什么?-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?</a></span></li><li><span><a href="#用tile函数去创建一个-8x8的棋盘样式矩阵" data-toc-modified-id="用tile函数去创建一个-8x8的棋盘样式矩阵-21"><span class="toc-item-num">21&nbsp;&nbsp;</span>用tile函数去创建一个 8x8的棋盘样式矩阵</a></span></li><li><span><a href="#对一个5x5的随机矩阵做归一化" data-toc-modified-id="对一个5x5的随机矩阵做归一化-22"><span class="toc-item-num">22&nbsp;&nbsp;</span>对一个5x5的随机矩阵做归一化</a></span></li><li><span><a href="#创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？" data-toc-modified-id="创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？-23"><span class="toc-item-num">23&nbsp;&nbsp;</span>创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？</a></span></li><li><span><a href="#一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？" data-toc-modified-id="一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？-24"><span class="toc-item-num">24&nbsp;&nbsp;</span>一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？</a></span></li><li><span><a href="#给定一个一维数组，对其在3到8之间的所有元素负数" data-toc-modified-id="给定一个一维数组，对其在3到8之间的所有元素负数-25"><span class="toc-item-num">25&nbsp;&nbsp;</span>给定一个一维数组，对其在3到8之间的所有元素负数</a></span></li><li><span><a href="#下面脚本运行后的结果是什么?" data-toc-modified-id="下面脚本运行后的结果是什么?-26"><span class="toc-item-num">26&nbsp;&nbsp;</span>下面脚本运行后的结果是什么?</a></span></li><li><span><a href="#考虑一个整数向量Z,下列表达合法的是哪个?" data-toc-modified-id="考虑一个整数向量Z,下列表达合法的是哪个?-27"><span class="toc-item-num">27&nbsp;&nbsp;</span>考虑一个整数向量Z,下列表达合法的是哪个?</a></span></li><li><span><a href="#下列表达式的结果分别是什么?" data-toc-modified-id="下列表达式的结果分别是什么?-28"><span class="toc-item-num">28&nbsp;&nbsp;</span>下列表达式的结果分别是什么?</a></span></li><li><span><a href="#如何从零位对浮点数组做舍入-?" data-toc-modified-id="如何从零位对浮点数组做舍入-?-29"><span class="toc-item-num">29&nbsp;&nbsp;</span>如何从零位对浮点数组做舍入 ?</a></span></li><li><span><a href="#如何找到两个数组中的共同元素?" data-toc-modified-id="如何找到两个数组中的共同元素?-30"><span class="toc-item-num">30&nbsp;&nbsp;</span>如何找到两个数组中的共同元素?</a></span></li><li><span><a href="#如何忽略所有的-numpy-警告(尽管不建议这么做)?" data-toc-modified-id="如何忽略所有的-numpy-警告(尽管不建议这么做)?-31"><span class="toc-item-num">31&nbsp;&nbsp;</span>如何忽略所有的 numpy 警告(尽管不建议这么做)?</a></span></li><li><span><a href="#下面的表达式是正确的吗?" data-toc-modified-id="下面的表达式是正确的吗?-32"><span class="toc-item-num">32&nbsp;&nbsp;</span>下面的表达式是正确的吗?</a></span></li><li><span><a href="#如何得到昨天，今天，明天的日期?" data-toc-modified-id="如何得到昨天，今天，明天的日期?-33"><span class="toc-item-num">33&nbsp;&nbsp;</span>如何得到昨天，今天，明天的日期?</a></span></li><li><span><a href="#如何得到所有与2016年7月对应的日期？" data-toc-modified-id="如何得到所有与2016年7月对应的日期？-34"><span class="toc-item-num">34&nbsp;&nbsp;</span>如何得到所有与2016年7月对应的日期？</a></span></li><li><span><a href="#如何直接在位计算(A+B)*(-A/2)(不建立副本)?" data-toc-modified-id="如何直接在位计算(A+B)*(-A/2)(不建立副本)?-35"><span class="toc-item-num">35&nbsp;&nbsp;</span>如何直接在位计算(A+B)*(-A/2)(不建立副本)?</a></span></li><li><span><a href="#用五种不同的方法去提取一个随机数组的整数部分" data-toc-modified-id="用五种不同的方法去提取一个随机数组的整数部分-36"><span class="toc-item-num">36&nbsp;&nbsp;</span>用五种不同的方法去提取一个随机数组的整数部分</a></span></li><li><span><a href="#创建一个5x5的矩阵，其中每行的数值范围从0到4" data-toc-modified-id="创建一个5x5的矩阵，其中每行的数值范围从0到4-37"><span class="toc-item-num">37&nbsp;&nbsp;</span>创建一个5x5的矩阵，其中每行的数值范围从0到4</a></span></li><li><span><a href="#通过考虑一个可生成10个整数的函数，来构建一个数组" data-toc-modified-id="通过考虑一个可生成10个整数的函数，来构建一个数组-38"><span class="toc-item-num">38&nbsp;&nbsp;</span>通过考虑一个可生成10个整数的函数，来构建一个数组</a></span></li><li><span><a href="#创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1" data-toc-modified-id="创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1-39"><span class="toc-item-num">39&nbsp;&nbsp;</span>创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1</a></span></li><li><span><a href="#创建一个长度为10的随机向量，并将其排序" data-toc-modified-id="创建一个长度为10的随机向量，并将其排序-40"><span class="toc-item-num">40&nbsp;&nbsp;</span>创建一个长度为10的随机向量，并将其排序</a></span></li><li><span><a href="#对于一个小数组，如何用比-np.sum更快的方式对其求和？" data-toc-modified-id="对于一个小数组，如何用比-np.sum更快的方式对其求和？-41"><span class="toc-item-num">41&nbsp;&nbsp;</span>对于一个小数组，如何用比 np.sum更快的方式对其求和？</a></span></li><li><span><a href="#对于两个随机数组A和B，检查它们是否相等" data-toc-modified-id="对于两个随机数组A和B，检查它们是否相等-42"><span class="toc-item-num">42&nbsp;&nbsp;</span>对于两个随机数组A和B，检查它们是否相等</a></span></li><li><span><a href="#创建一个只读数组(read-only)" data-toc-modified-id="创建一个只读数组(read-only)-43"><span class="toc-item-num">43&nbsp;&nbsp;</span>创建一个只读数组(read-only)</a></span></li><li><span><a href="#将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式" data-toc-modified-id="将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式-44"><span class="toc-item-num">44&nbsp;&nbsp;</span>将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式</a></span></li><li><span><a href="#创建一个长度为10的向量，并将向量中最大值替换为1" data-toc-modified-id="创建一个长度为10的向量，并将向量中最大值替换为1-45"><span class="toc-item-num">45&nbsp;&nbsp;</span>创建一个长度为10的向量，并将向量中最大值替换为1</a></span></li><li><span><a href="#创建一个结构化数组，并实现-x-和-y-坐标覆盖-[0,1]x[0,1]-区域" data-toc-modified-id="创建一个结构化数组，并实现-x-和-y-坐标覆盖-[0,1]x[0,1]-区域-46"><span class="toc-item-num">46&nbsp;&nbsp;</span>创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域</a></span></li><li><span><a href="#给定两个数组X和Y，构造Cauchy矩阵C-(Cij-=1/(xi---yj))" data-toc-modified-id="给定两个数组X和Y，构造Cauchy矩阵C-(Cij-=1/(xi---yj))-47"><span class="toc-item-num">47&nbsp;&nbsp;</span>给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))</a></span></li><li><span><a href="#打印每个numpy标量类型的最小值和最大值？" data-toc-modified-id="打印每个numpy标量类型的最小值和最大值？-48"><span class="toc-item-num">48&nbsp;&nbsp;</span>打印每个numpy标量类型的最小值和最大值？</a></span></li><li><span><a href="#如何打印一个数组中的所有数值?" data-toc-modified-id="如何打印一个数组中的所有数值?-49"><span class="toc-item-num">49&nbsp;&nbsp;</span>如何打印一个数组中的所有数值?</a></span></li><li><span><a href="#给定标量时，如何找到数组中最接近标量的值？" data-toc-modified-id="给定标量时，如何找到数组中最接近标量的值？-50"><span class="toc-item-num">50&nbsp;&nbsp;</span>给定标量时，如何找到数组中最接近标量的值？</a></span></li></ul></div>

NumPy是由Python做数据分析所必须掌握的基础库之一，它可以用来存储和处理大型矩阵，并且Numpy提供了许多高级的数值编辑工具，如：矩阵数据类型、矢量处理，以及精密的运算库，转为进行严格的数字处理而产生。  

## 导入numpy库简写为np

In [3]:
import numpy as np

## 打印numpy的版本和配置说明  

In [3]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['c:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'c:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['c:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'c:/Anaconda3\\Library\\include']


## 创建一个长度为10的空向量

In [4]:
Z = np.empty(10)
print(Z)

[           nan 0.0000000e+000 1.1356122e-311 2.0236929e-320
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000]


## 如何找到任何一个数组的内存大小？

In [5]:
print(Z.itemsize,Z.size)

8 10


## 如何从命令行得到numpy中add函数的说明文档?

In [7]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
       [ 0.]])

>

## 创建一个长度为10并且除了第五个值为1的空向量

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 创建一个值域范围从10到49的向量

In [11]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 反转一个向量(第一个元素变为最后一个)

In [17]:
Z = np.arange(50)
print(Z)
print('*'*50)
Z = Z[::-1]
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
**************************************************
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 创建一个 3x3 并且值从0到8的矩阵

In [18]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [21]:
Z = np.array([[1,2,0,0,4,0]])
print(Z)
print('*'*50)
nz = np.nonzero(Z)
print(nz)

[[1 2 0 0 4 0]]
**************************************************
(array([0, 0, 0], dtype=int64), array([0, 1, 4], dtype=int64))


## 创建一个 3x3 的单位矩阵

In [23]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 创建一个 3x3x3的随机数组

In [25]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.09789288 0.71612683 0.23977311]
  [0.23716254 0.19929478 0.16458241]
  [0.42484153 0.16897259 0.66474951]]

 [[0.56150498 0.80143584 0.37125523]
  [0.83716834 0.04291838 0.48704709]
  [0.59074829 0.438888   0.44927112]]

 [[0.03646418 0.4836803  0.17348906]
  [0.85631706 0.46187264 0.61327845]
  [0.8802533  0.47096434 0.2985315 ]]]


## 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [27]:
Z = np.random.random((10,10))
print(Z)
print('*'*50)
print(np.max(Z),np.min(Z))

[[0.79092675 0.99275092 0.98649245 0.81502287 0.51616486 0.1639619
  0.95721198 0.05817157 0.4303487  0.21832215]
 [0.2608683  0.8273142  0.40129929 0.60474752 0.35856324 0.25667051
  0.04223669 0.38263282 0.82286095 0.52587565]
 [0.74738011 0.85691616 0.27814088 0.02987201 0.5297273  0.97648336
  0.48047005 0.93790549 0.43761015 0.41089575]
 [0.96793911 0.29215611 0.84181734 0.48602103 0.50928493 0.35309606
  0.42376059 0.14369878 0.42161893 0.32528839]
 [0.22799153 0.0890188  0.13660195 0.22929835 0.32235542 0.86805763
  0.6259362  0.0110531  0.2501834  0.21292095]
 [0.41126469 0.02066989 0.00928629 0.07730962 0.27419297 0.00254452
  0.6242138  0.67629351 0.00888517 0.37450388]
 [0.21279442 0.51062646 0.35982213 0.70334421 0.18605554 0.61393246
  0.19580137 0.66315126 0.22782093 0.11754729]
 [0.26526216 0.44936164 0.81977814 0.95621093 0.34212947 0.70870503
  0.98862808 0.14917107 0.90292028 0.21694779]
 [0.60742367 0.10092437 0.82378723 0.3406292  0.58551188 0.20049238
  0.93083538 

## 创建一个长度为30的随机向量并找到它的平均值

In [33]:
Z = np.random.random(30)
print(Z,np.size(Z))
print('*'*50)
print(Z.mean())

[0.66123539 0.72672585 0.7108322  0.11603422 0.10368161 0.81135862
 0.12635675 0.81220776 0.73529156 0.24084981 0.76647878 0.02108078
 0.2342558  0.81670909 0.94357044 0.61129184 0.77230142 0.54706934
 0.73684212 0.18634212 0.22848226 0.71854055 0.58711918 0.57589547
 0.23647689 0.16714183 0.90525807 0.20651969 0.16706557 0.06064701] 30
**************************************************
0.4844554007571869


## 创建一二维数组，其中边界值为1，其余值为0

In [46]:
Z = np.ones((10,10))
print(Z)
print('*'*50)
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
**************************************************
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 对于一个存在在数组，如何添加一个用0填充的边界?

In [50]:
Z = np.ones((10,10))
print(Z)
print('*'*50)
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
**************************************************
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 以下表达式运行的结果分别是什么?

In [58]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False
0.3 0.30000000000000004


## 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [63]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

##  创建一个8x8 的矩阵，并且设置成棋盘样式

In [71]:
Z = np.zeros(64).reshape(8,8)
print(Z,Z.shape)
print('*'*50)
Z[::-2,::2] = 1
Z[::2,::-2] = 1
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] (8, 8)
**************************************************
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [72]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


##  用tile函数去创建一个 8x8的棋盘样式矩阵

In [79]:
Z = np.array([[0,1],[1,0]])
print(Z)
print('*'*50)
Z = np.tile(Z,(4,4))
print(Z,Z.shape)

[[0 1]
 [1 0]]
**************************************************
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] (8, 8)


## 对一个5x5的随机矩阵做归一化  
(提示: (x - min) / (max - min))

In [83]:
Z = np.random.random((5,5))
print(Z)
print('*'*50)
a = (Z - Z.min())/(Z.max() - Z.min())
print(a)

[[0.93895879 0.96565234 0.28839313 0.63002159 0.43967215]
 [0.3041305  0.56438816 0.49356036 0.44093388 0.48763655]
 [0.31225993 0.33420538 0.76456388 0.355359   0.59914825]
 [0.56264489 0.07405579 0.34867603 0.74955956 0.39276276]
 [0.37158098 0.71231311 0.41715897 0.55334441 0.47801313]]
**************************************************
[[0.97006095 1.         0.24039723 0.62356207 0.41006928]
 [0.258048   0.5499487  0.47050941 0.41148442 0.46386536]
 [0.26716583 0.29177949 0.7744625  0.31550504 0.58893505]
 [0.54799348 0.         0.30800954 0.7576339  0.35745649]
 [0.33369934 0.7158589  0.38481887 0.53756222 0.4530719 ]]


## 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [86]:
color = np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


## 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [87]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 给定一个一维数组，对其在3到8之间的所有元素负数

In [98]:
Z = np.arange(11)
print(Z)
print('*'*50)
a = (Z>3) & (Z<8) 
Z[a] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
**************************************************
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 下面脚本运行后的结果是什么?

In [99]:
print(sum(range(5),-1))

9


## 考虑一个整数向量Z,下列表达合法的是哪个?

## 下列表达式的结果分别是什么?

In [102]:
print(np.array(0) /np.array(0))
print(np.array(0) //np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


##  如何从零位对浮点数组做舍入 ?

In [105]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print('*'*50)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 1.57641675 -9.99396277 -1.63759239 -9.25922603 -8.81597337 -1.95440653
  4.60983266 -3.71687475  9.32582767 -7.49565124]
**************************************************
[  2. -10.  -2. -10.  -9.  -2.   5.  -4.  10.  -8.]


## 如何找到两个数组中的共同元素?

In [107]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 3 8]


## 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [110]:
defaults=np.seterr(all="ignore")
Z=np.ones(1) /0
_=np.seterr(**defaults)

## 下面的表达式是正确的吗?

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
c:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


## 如何得到昨天，今天，明天的日期?

In [8]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tommorrow)

2020-01-19
2020-01-20
2020-01-21


## 如何得到所有与2016年7月对应的日期？

In [21]:
Z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [28]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A)
print(B)
print(C)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]


In [30]:
print(np.add(A,B))
print(np.divide(A,B))
print(np.multiply(A,B))
print(np.negative(A))

[3. 3. 3.]
[0.5 0.5 0.5]
[2. 2. 2.]
[-1. -1. -1.]


## 用五种不同的方法去提取一个随机数组的整数部分

In [31]:
Z = np.random.uniform(0,10,10)
print(Z)

[9.26807865 5.24152716 2.50802403 4.44263193 1.25019563 0.38806938
 6.79232981 7.15136656 7.16190223 0.39823721]


## 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [38]:
Z = np.arange(5)
print(Z)
Z = np.tile(Z,(5,1))
print(Z)

[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 通过考虑一个可生成10个整数的函数，来构建一个数组

In [42]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [47]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 创建一个长度为10的随机向量，并将其排序

In [50]:
Z = np.random.random(10)
print (np.sort(Z))

[0.05086982 0.13353341 0.23123904 0.28337795 0.28985241 0.29902768
 0.48623928 0.51665304 0.56718066 0.6281717 ]


## 对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [51]:
Z = np.arange(10)
print(np.add.reduce(Z))

45


## 对于两个随机数组A和B，检查它们是否相等

In [54]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.allclose(A,B))
print(np.equal(A,B))

False
[False False  True  True  True]


## 创建一个只读数组(read-only)

In [56]:
Z=np.zeros(10)
Z.flags.writeable = False
print(Z.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


## 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [57]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.31144618 0.77674353 0.31253838 0.86792315 1.17677951 0.59310429
 0.63632594 0.96234784 0.76858453 1.1088611 ]
[1.15957365 0.54157193 1.14836198 1.49929561 0.69658371 0.75094867
 1.08406216 1.46057782 0.75983322 0.49466247]


## 创建一个长度为10的向量，并将向量中最大值替换为1

In [58]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.39522202 0.03163375 0.         0.15644543 0.53722287 0.67158535
 0.63486271 0.33256816 0.21188333 0.48514314]


## 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [60]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [61]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


## 打印每个numpy标量类型的最小值和最大值？

In [64]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 如何打印一个数组中的所有数值?

In [65]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

## 给定标量时，如何找到数组中最接近标量的值？

In [66]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

65
