<h1>NumPy参考手册代码学习_01<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#数组对象" data-toc-modified-id="数组对象-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>数组对象</a></span><ul class="toc-item"><li><span><a href="#N维数组" data-toc-modified-id="N维数组-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>N维数组</a></span></li><li><span><a href="#标量" data-toc-modified-id="标量-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>标量</a></span></li><li><span><a href="#数据类型对象（dtype）" data-toc-modified-id="数据类型对象（dtype）-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>数据类型对象（dtype）</a></span></li><li><span><a href="#索引" data-toc-modified-id="索引-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>索引</a></span></li></ul></li></ul></div>

# 数组对象
## N维数组
* 尺寸为二乘三的二维数组，由四个字节的整数元素组成，用Python容器语法对数组进行索引，切片可以生成数组的视图

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


In [3]:
x[1,2]

6

In [6]:
y = x[:,1]
print(y)
y[0] = 9
print(y)
print(x)

[2 5]
[9 5]
[[1 9 3]
 [4 5 6]]


* ndarray构造函数创建数组

In [7]:
import numpy
array = numpy.ndarray(shape=(2,2), dtype=np.float, order='F')
print(array)

[[1.26410987e-311 1.33511562e-306]
 [0.00000000e+000 5.73116149e-322]]


In [9]:
# 进行偏移量
array = numpy.ndarray((2,), buffer=np.array([1,2,3]), offset=np.int_().itemsize, dtype=np.int)
print(array) # offset = 1*itemsize, i.e. skip first element

[2 3]


* 内存布局方法  

|方法|描述|
|---|---|
|ndarray.flags|有关数组内存布局信息|
|ndarray.shape|数组维度的元组|
|ndarray.strides|遍历数组时每个维度中的字节元组|
|ndarray.ndim|数组维数|
|ndarray.data|Python缓冲区对象指向数组的数据的开头|
|ndarray.size|数组中元素数|
|ndarray.itemsize|一个数组元素的长度以字节为单位|
|ndarray.nbytes|数组元素消耗的总字节数|
|ndarray.base|如果内存来自其他对象，则为基础对象|

* 数据类型  

|方法|描述|
|---|---|
|ndarray.dtype|数组元素的数据类型|

* 其他属性  

|方法|描述|
|---|---|
|ndarray.T|转置数组|
|ndarray.real|数组的真实部分|
|ndarray.imag|数组的虚部|
|ndarray.flat|数组上的一维迭代器|
|ndarray.ctypes|一个简化数组与ctypes模块交互的对象|

* **数组方法**    
数组的方法是比较常用的，一个ndarray对象具有某种方式在数组，典型的返回一个数组结果操作的许多方法。主要范分为：数组转换、形状操作、项目选择和操作、计算

**数组转换**  

1.  ndarray.item(*args) | 将数组元素复制到标准Python标量并返回它，返回Python的数据格式，而不是ndarray的数据格式。如果数据为一个整数，表示按照顺序进行数数

In [16]:
import numpy as np
np.random.seed(123)
x = np.random.randint(9,size=(3,3))
print(x)
print(x.item(3))
print(x.item(7))
print(x.item((0,1)))
a = x.item((2,2))
print(x.item((2,2)))
print(type(a))

[[2 2 6]
 [1 3 6]
 [1 0 1]]
1
0
2
1
<class 'int'>


2.ndarray.tolist()|将数组做为a.ndim-levels申城嵌套的Python标量列表并返回。就是将ndarray数据类型转换成Python数据类型，同item一样不过返回的是Python的list，而不是单个值

In [26]:
# 二维
import numpy as np
a = np.array([[1.2],[3,4]])
a1 = list(a)
b1 = a.tolist()
print(type(a1))
print(type(b1))

<class 'list'>
<class 'list'>


In [31]:
# 标量
a = np.array(1)
print(a)
# a1 = list(a) # 报错
a1 = a.tolist()
print(a1,type(a1))

1
1 <class 'int'>


In [33]:
# 一维
a = np.array([1,2,3,4,5])
a1 = list(a)
print(a1,type(a1))

[1, 2, 3, 4, 5] <class 'list'>


* 3.ndarray.itemset|将标量插入数组（如果可能，讲标了转换为数组的dtype）

In [38]:
import numpy as np
np.random.seed(123)
x = np.random.randint(9, size=(3,3))
print(x)
print(x.itemset((2,2),9))  # 对应2,2位置插入9
print(x)

[[2 2 6]
 [1 3 6]
 [1 0 1]]
None
[[2 2 6]
 [1 3 6]
 [1 0 9]]


* ndarray.tostring/tobytes| 构造包含数组中原始数据字节的Python字节

In [43]:
x = np.array([[0, 1], [2, 3]], dtype='<u2')
print(x.tostring())
print(x.tobytes('C') == x.tobytes())
print(x.tobytes('F'))

b'\x00\x00\x01\x00\x02\x00\x03\x00'
True
b'\x00\x00\x02\x00\x01\x00\x03\x00'


* ndarray.tofile| 将数组做为文本或二进制写入文件（默认）

In [45]:
x = np.array([[0, 1], [2, 3]], dtype='<u2')
x.tobytes()

b'\x00\x00\x01\x00\x02\x00\x03\x00'

* ndarray.dump(file)|j将数组的pickle转储到指定文件

* ndarray.dumps()| 以字符串形式返回数组的pickle

* ndarray.atype(dtype[,order,casting,...])| 数组的副本，强制转换为指定的类型

In [70]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

[1 2 3 4 5] int32
float64


* ndarray.byteswap| 交交换数组元素的字节

In [71]:
A = np.array([1, 256, 8755], dtype=np.int16)
print(list(map(hex, A)))
A.byteswap(inplace=True)
print(list(map(hex, A)))

['0x1', '0x100', '0x2233']
['0x100', '0x1', '0x3322']


* ndarray.copy| 深拷贝，返回数组的副本

In [72]:
x = np.array([[1,2,3],[4,5,6]], order='F')
y = x
# 更改原数组中的某一个值
x[0][0] = 100
# 查看两个数组值变化都改变了，因为这是引用方式
print(x)
print(y)

[[100   2   3]
 [  4   5   6]]
[[100   2   3]
 [  4   5   6]]


In [73]:
x = np.array([[1,2,3],[4,5,6]], order='F')
y = x.copy()
# 更改原数组中的某一个值
x[0][0] = 100
# 采用深拷贝不影响
print(x)
print(y)

[[100   2   3]
 [  4   5   6]]
[[1 2 3]
 [4 5 6]]


* ndarray.view([dtype,type])| 具有相同数据的数组的新视图

In [75]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])
print(x)
y = x.view(dtype=np.int16, type=np.matrix)
print(y)

[(1, 2)]
[[513]]


In [76]:
x = np.array([(1, 2),(3,4)], dtype=[('a', np.int8), ('b', np.int8)])
xv = x.view(dtype=np.int8).reshape(-1,2)
print(xv)

[[1 2]
 [3 4]]


* ndarray.getfield| filter回给定数组的字段做为特定类型

In [82]:
x1 = np.diag([1.+1.j]*2)
x1[1, 1] = 2 + 4.j
print(x1)
print()
x1.getfield(np.float64)
print(x1)
print()
x1.getfield(np.float64, offset=8)
print(x1)

[[1.+1.j 0.+0.j]
 [0.+0.j 2.+4.j]]

[[1.+1.j 0.+0.j]
 [0.+0.j 2.+4.j]]

[[1.+1.j 0.+0.j]
 [0.+0.j 2.+4.j]]


* ndarray.setflags| 分别设置数组标志WRITEABLE，ALIGNED，（WRITEBACKIFCOPY和UPDATEIFCOPY）

In [84]:
y = np.array([[3, 1, 7],
...               [2, 0, 0],
...               [8, 5, 9]])
print(y)

[[3 1 7]
 [2 0 0]
 [8 5 9]]


In [85]:
print(y.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [87]:
y.setflags(write=0, align=0)
print(y.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : False
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


* ndarray.fill| 使用标量进行填充

In [89]:
a = np.array([1,2])
print(a)
print('*'*50)
a.fill(0)
print(a)

[1 2]
**************************************************
[0 0]


**形状操作**   
对于重新n整形、调整大小和转置，单个元组参数可以用被解释为n元组的整数替换。

* ndarray.reshape| 返回包含具有新形状的相同数据的数组

In [94]:
a = np.arange(16).reshape(4,-1)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


* ndarray.resize| 就地更改数组的形状和大小

In [99]:
a = np.array([[0, 1], [2, 3]], order='F')
print(a)
a.resize((2, 1))
print(a)

[[0 1]
 [2 3]]
[[0]
 [2]]
[[0]
 [2]]


In [100]:
# reshape和resize是一对，前者是不改变原数组的形状，后者是改变原数组的形状
a = np.arange(16)
a.reshape(4,-1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [102]:
a = np.arange(16)
a.resize(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


* ndarray.flatten| 将折叠的数组的副本返回到一个维度

* ndarray.ravel| 返回一个扁平的数组

In [115]:
# flatten和ravel也是一对，内容同上
a = np.arange(16).reshape(4,4)
print(a)
a.flatten()[:] =16
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [113]:
a = np.arange(16).reshape(4,4)
print(a)
a.ravel()[...]=16
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]


* ndarray.transpose| 转置操作类似于.T

In [117]:
a = np.arange(16).reshape(4,4)
print(a)
np.transpose(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

* ndarray.swapaxes| 交换数组中的视图，对轴axis1和axis互换

In [121]:
a = np.arange(16).reshape(4,4)
print(a)
print('*'*50)
print(np.swapaxes(a,0,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
**************************************************
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [122]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [123]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

* ndarray.squeeze| 从形状去除单维输出一个不会改变原数组的形状

In [130]:
e= np.arange(10).reshape(1,1,10)
print(e.shape,e,sep='\n')

(1, 1, 10)
[[[0 1 2 3 4 5 6 7 8 9]]]


In [139]:
a = np.squeeze(e,axis=(0))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [126]:
print(x)

[[[0]
  [1]
  [2]]]


**项目选择和操作**  
对于采用 axis 关键字的数组方法，默认为 None。 如果axis为 None ，则将数组视为1-D数组。 轴的 任何其他值表示操作应继续进行的维度。

* ndarray.take(indices[, axis, out, mode])| 返回由给定索引处的a元素组成的数组

In [140]:
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

array([4, 3, 6])

* ndarray.put(indices, values[, mode])| 为索引中的所有n设置。a.flat[n] = value[n]

In [141]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [142]:
# mode有三：raise引发一个错误，wrap-不提示错误，clip，如果引发一个错误，如果这个错误是由目标数组引起的
# 将被修改
a = np.arange(5)
np.put(a, 22, -5, mode='clip')
a

array([ 0,  1,  2,  3, -5])

* ndarray.repeat(repeats[, axis])/tile|重复数组元素,tile是把数组做为一个整体进行重复

In [162]:
x = np.array([[1,2],[3,4]])
print(x)
print('*'*50)
print(np.repeat(x, 2,axis=1))
print('*'*50)
print(np.tile(x,(4))) # （4，）第一个参数表示向行重复几遍，第二个参数表示向列重复几遍


[[1 2]
 [3 4]]
**************************************************
[[1 1 2 2]
 [3 3 4 4]]
**************************************************
[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


* ndarray.chose(choices[, out, mode])| 使用索引数组从一组选项中构造新数组

In [197]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index = np.array([0,0,0,0])   # 对应的每一行索要选择的内容
np.choose(index,a.T)

array([ 1,  4,  7, 10])

In [201]:
# choose第一个参数：要选择成什么样的数组，数组中的内容都是表示下标。第二个参数：表示选择什么内容
op = np.array([[0,1,2,0],[1,0,2,0]])
ip = np.array([100,200,300,400])
np.choose(op,ip)

array([[100, 200, 300, 100],
       [200, 100, 300, 100]])

* ndarray.sort([axis, kind, order])| 就地排序

In [227]:
# 这个排序可以按照行的方向排序，还可以按照列的方向排序，都是升序
a = np.array([[1,4], [3,1]])
print(a)
print('*'*50)
print(np.sort(a,axis=1))
print('*'*50)
print(np.sort(a,axis=0))

[[1 4]
 [3 1]]
**************************************************
[[4 1]
 [3 1]]
**************************************************
[[1 1]
 [3 4]]


In [228]:
# 对于逆序的话，没有现成的方法，可以采取取负再取负的方式
print(-np.sort(-a,axis=1))

[[4 1]
 [3 1]]


* argsort([axis, kind, order])| 与上面相同不过返回的索引

In [229]:
a = np.array([[1,4], [3,1]])
print(a)
print('*'*50)
print(np.argsort(a,axis=1))

[[1 4]
 [3 1]]
**************************************************
[[0 1]
 [1 0]]


* ndarray.partition(kth[, axis, kind, order])| 重新排列数组中的元素，使得第k个位置的元素值位于排列数组中的位置

In [241]:
# partition是分区的意思，设定一个数值，比这个数值大的放到后面，小的放到前面
a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])
print(np.sort(a))
print(np.argpartition(a, 4))

[0 0 3 3 4 4 4 6 9 9]
[6 9 4 3 7 2 1 5 8 0]


* ndarray.argpartition(kth[, axis, kind, order])| 重新排列数组中的元素，使得第k个位置的元素值位于排列数组中的位置，返回的是索引

* ndarray.searchsorted(v[, side, sorter])| 查找应在其中插入v的元素以维护顺序的索引，side表示方向  
left = a[i-1] < v <= a[i]  
right = a[i-1] <= v < a[i]  
这个比较有用

In [244]:
a = np.array([1,2,3,4,5])
np.searchsorted(a,5)

4

* ndarray.nonzero()| 返回非零元素的索引

In [245]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
print(np.nonzero(x))

[[3 0 0]
 [0 4 0]
 [5 6 0]]
(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))


* ndarray.compress(condition[, axis, out])| 沿给定轴返回此数组的选定切片

In [248]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print('*'*50)
print(np.compress([True,False],a,axis=1))
print('*'*50)
print(np.compress([1,0],a,axis=1))

[[1 2]
 [3 4]
 [5 6]]
**************************************************
[[1]
 [3]
 [5]]
**************************************************
[[1]
 [3]
 [5]]


* ndarray.diagonal([offset, axis1, axis2])| 返回指定的对角线

In [249]:
a = np.arange(4).reshape(2,2)
print(a)
print('*'*50)
print(np.diagonal(a))

[[0 1]
 [2 3]]
**************************************************
[0 3]


In [252]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [251]:
a.diagonal(0,  # Main diagonals of two arrays created by skipping
...            0,  # across the outer(left)-most axis last and
...            1)  # the "middle" (row) axis first.

array([[0, 6],
       [1, 7]])

**计算**   
其中许多方法都采用名为 axis 的参数。在这种情况下，如果 axis 为 None （默认值），则将数组视为1-D数组，并对整个数组执行操作。 如果self是0维数组或数组标量，则此行为也是默认行为。 （数组标量是类型/类float32，float64等的实例，而0维数组是包含恰好一个数组标量的ndarray实例。）  
如果 axis 是整数，则操作在给定轴上完成（对于可沿给定轴创建的每个1-D子数组）。

* ndarray.max/min([axis，out，keepdims，initial，...]）/argmax/argmin([axis, out])| 返回最大最小以及其索引的方法

In [253]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [256]:
print(a.max(axis=1))
print('*'*50)
print(a.min(axis=0))
print('*'*50)
print(a.argmax(axis=1))
print('*'*50)
print(a.argmin(axis=0))

[4 9]
**************************************************
[0 1 2 3 4]
**************************************************
[4 4]
**************************************************
[0 0 0 0 0]


* ndarray.ptp([axis, out, keepdims])| 沿着给定轴的方向求峰值（最大值-最小值）

In [257]:
x = np.arange(4).reshape((2,2))
print(x)
print('*'*50)
print(np.ptp(x,axis=1))

[[0 1]
 [2 3]]
**************************************************
[1 1]


* ndarray.clip([min，max，out])| 返回值限制为的数组[max,min]

In [262]:
a = np.arange(10)
print(a)
print('*'*50)
print(np.clip(a, 1, 8))
print('*'*50)
print(np.clip(a, 3, 6, out=a))

[0 1 2 3 4 5 6 7 8 9]
**************************************************
[1 1 2 3 4 5 6 7 8 8]
**************************************************
[3 3 3 3 4 5 6 6 6 6]


* ndarray.conj()| 符合共轭的所有元素

In [265]:
x = np.eye(2) + 1j * np.eye(2)
print(x)
print('*'*50)
print(np.conjugate(x))

[[1.+1.j 0.+0.j]
 [0.+0.j 1.+1.j]]
**************************************************
[[1.-1.j 0.-0.j]
 [0.-0.j 1.-1.j]]


* ndarray.round()| 四舍五入

In [266]:
np.around([0.37, 1.64])

array([0., 2.])

* ndarray.trace([offset, axis1, axis2, dtype, out])| 返回数组对角线的总和

In [270]:
a = np.arange(4).reshape((2,2))
print(a)
print('*'*50)
print(np.trace(a))

[[0 1]
 [2 3]]
**************************************************
3


* ndarray.sum/cumsum([axis, dtype, out])| 求和和求累加

In [271]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

1

In [272]:
np.cumsum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

array([0, 0, 0, 1], dtype=int32)

* ndarray.mean/var/std| 求均值

In [274]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [275]:
np.std(a)

1.118033988749895

In [276]:
np.var(a)

1.25

* ndarray.prod/cumprod| 求乘积和累乘

In [278]:
np.prod([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

0

In [277]:
np.cumprod([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

array([0, 0, 0, 0], dtype=int32)

* ndarray.all/any| 如果所有元素都为True返回为True，如果任何一个元素，返回真，一个评估为True

In [279]:
np.all([[True,False],[True,True]])

False

In [280]:
np.any([[True,False],[True,True]])

True

**算术、矩阵乘法和比较运算**

|方法|描述|
|---|---|
|ndarray._lt_(self, value, /)	|返回 self<value.|
|ndarray._le_(self, value, /)	|返回 self<=value.|
|ndarray._gt_(self, value, /)	|返回 self>value.|
|ndarray._ge_(self, value, /)	|返回 self>=value.|
|ndarray._eq_(self, value, /)	|返回 self==value.|
|ndarray._ne_(self, value, /)	|返回 self!=value.| 
|ndarray._bool_(self,/)	|self!=0|
|ndarray.\__add__(self, value, /)	|返回 self+value.|
|ndarray.\__sub__(self, value, /)	|返回 self-value.|
|ndarray.\__mul__(self, value, /)	|返回 self*value.|
|ndarray.\__truediv__(self, value, /)	|返回 self/value.|
|ndarray.\__floordiv__(self, value, /)	|返回 self//value.|
|ndarray.\__mod__(self, value, /)	|返回 self%value.|
|ndarray.\__divmod__(self, value, /)	|返回 divmod(self, value).|
|ndarray.\__pow__(self, value[, mod])	|返回 pow(self, value, mod).|
|ndarray.\__lshift__(self, value, /)	|返回 self<<value.|
|ndarray.\__rshift__(self, value, /)	|返回 self>>value.|
|ndarray.\__and__(self, value, /)	|返回 self&value.|
|ndarray.\__or__(self, value, /)	|返回 self|
|ndarray.\__xor__(self, value, /)	|返回 self^value.|
|ndarray.\__iadd__(self, value, /)	返回 self+=value。|
|ndarray.\__isub__(self, value, /)	返回 self==value。|
|ndarray.\__imul__(self, value, /)	返回 self*=value。|
|ndarray.\__itruediv__(self, value, /)	返回 self/=value。|
|ndarray.\__ifloordiv__(self, value, /)	返回 self//=value。|
|ndarray.\__imod__(self, value, /)	返回 self％=value。|
|ndarray.\__ipow__(self, value, /)	返回 self**=value。|
|ndarray.\__ilshift__(self, value, /)	返回 self<<=value。|
|ndarray.\__irshift__(self, value, /)	返回 self>>=value。|
|ndarray.\__iand__(self, value, /)	返回 self&=value。|
|ndarray.\__ior__(self, value, /)	返回 self|
|ndarray.\__ixor__(self, value, /)	返回 self^=value。|
|ndarray.\__matmul__(self, value, /)	返回 self@value。|

**特殊方法**

|方法|描述|
|---|---|
|ndarray._copy__()	|如果使用的copy.copy是所谓的数组上。|
|ndarray._deepcopy__()	|如果使用的copy.deepcopy是所谓的数组上。|
|ndarray._reduce__()	|用于 pickling。|
|ndarray._setstate__（州，/）	|用于unpickling|
|ndarray._new__(*args, **kwargs)	创建并返回一个新对象。|
|ndarray._array__()	|如果没有给出dtype，则返回对self的新引用;如果dtype与数组的当前dtype不同，则返回提供的数据类型的新数组。|
|ndarray._array_wrap__()	
|ndarray._len__(self, /)	|返回 len(self)。|
|ndarray._getitem__(self, key, /)	|返回 self[key]。|
|ndarray.__setitem__(self, key, value, /)	|将 self[key] 设置为value。|
|ndarray.__contains__(self, key, /)	|返回 self 的 key。|
|ndarray.__int__(self)	|none|
|ndarray.__float__(self)	|none|
|ndarray.__complex__()	|none
|ndarray.__str__(self, /)	|返回 str(self)。|
|ndarray.__repr__(self, /)	|返回 repr(self)。||

## 标量  
标量
Python只定义了一种特定数据类（只有一种整数类型，一种浮点类型等）。这在不需要关心数据在计算机中表示的所有方式的应用中是方便的。然而，对于科学计算，通常需要更多的控制。

在NumPy中，有24种新的基本Python类型来描述不同类型的标量。这些类型描述符主要基于CPython编写的C语言中可用的类型，其他几种类型与Python的类型兼容。

数组标量具有与之相同的属性和方法ndarrays。[1]这允许人们将数组中的项目部分地放在与数组相同的基础上，从而平滑混合标量和数组操作时产生的粗糙边缘。

数组标量存在于数据类型的层次结构中（请参见下图）。 可以使用层次结构检测它们：例如，如果Val是数组标量对象，则 isinstance(val，np.generic) 将返回 True。 或者，可以使用数据类型层次结构的其他成员来确定存在哪种数组标量。 因此，例如，如果val是复数值类型，则 isinstance(val，np.complexfloat) 将返回 True， 而如果 val 是灵活的itemsize数组类型之一（string、unicode、void）， 则 isinstance(val，np.Flexible) 将返回 True。

* 内置标量类型  
内置标量类型如下所示。连同它们的（主要是）C衍生的名称时，整数，浮点数，和复杂的数据类型也可使用位宽度约定，以便正确的大小的数组可以总是确保（例如int8，float64， complex128）。还提供了两个别名（intp和uintp）指向足以容纳C指针的整数类型。类似C的名称与字符代码相关联，如表中所示。但是，不鼓励使用字符代码。
一些标量类型基本上等同于基本的Python类型，因此从它们以及通用数组标量类型继承  

|数组标量类型|	相关的Python类型|
|---|---|
|int_	|IntType （仅限Python 2）|
|float_	|FloatType|
|complex_	|ComplexType|
|bytes_	|BytesType|
|unicode_	|UnicodeType|
|bool_	|兼容：Python bool	|
|bool8	|8位|
|byte	|兼容：C char	'b'
|short	|兼容：C短	'h'
|intc	|兼容：C int	'i'
|int_	|兼容：Python int	'l'
|longlong|	兼容：C长	'q'
|intp	|大到足以适合指针	'p'
|int8	|8位	
|int16	|16位	
|int32	|32位	
|int64	|64位	
|ubyte	|compatible：C unsigned char	'B'
|ushort	|兼容：C unsigned short	'H'
|uintc	|compatible：C unsigned int	'I'
|uint	|兼容：Python int	'L'
|ulonglong	|兼容：C长	'Q'
|uintp	|大到足以适合指针	'P'
|uint8	|8位	
|uint16	|16位	
|uint32	|32位	
|uint64	|64位	
|half	|	'e'
|single	|兼容：C浮动	'f'
|double	|兼容：C双	
|float_	兼容：Python float	'd'
|longfloat	|兼容：C长浮	'g'
|float16	|16位	
|float32	|32位	
|float64	|64位	
|float96	|96位，平台？	
|float128	|128位，平台？
|csingle	|	'F'
|complex_	|兼容：Python复杂	'D'
|clongfloat	|	'G'
|complex64	|两个32位浮点数	
|complex128	|两个64位浮点数	
|complex192	|两个96位浮动平台？	
|complex256	|两个128位浮点数，平台？
|object_	|任何Python对象	'O'
|bytes_	|兼容：Python字节	'S#'
|unicode_	|兼容：Python unicode / str	'U#'
|void		|'V#'

* 属性

|方法	|描述|
|---|---|
|generic.flags	|标志的整数值
|generic.shape	|数组维度的元组
|generic.strides|	每个维度中的字节元组步骤
|generic.ndim	|数组维数
|generic.data	|指向数据开始的指针
|generic.size	|gentype中的元素数量
|generic.itemsize	|一个元素的长度，以字节为单位
|generic.base	|基础对象
|generic.dtype	|获取数组数据描述符
|generic.real	|标量的真实部分
|generic.imag	|标量的虚部
|generic.flat	|标量的一维视图
|generic.T	|颠倒
|generic.array_interface	|数组协议：Python端
|generic.array_struct	|数组协议：struct
|generic.array_priority	|数组优先级。
|generic.array_wrap()	|sc .__ array_wrap __（obj）从数组返回标量

* 索引  
数组标量可以像0维数组一样索引：如果 x 是数组标量，  
x[()] 返回数组标量的副本  
x[...] 返回0维 ndarray  
x['field-name']返回字段 field-name中 的数组标量。（例如， x 可以包含字段，当它对应于结构化数据类型时。）

* 方法  

|方法	|描述|
|---|---|
|generic	|numpy标量类型的基类。
|generic.array()	|sc .__ array __（dtype）从带有指定dtype的标量返回0-dim数组
|generic.array_wrap()	|sc .__ array_wrap __（obj）从数组返回标量
|generic.squeeze()	|未实现（虚拟属性）
|generic.byteswap()	|未实现（虚拟属性）
|generic.reduce()	|泡菜的助手
|generic.setstate()	|
|generic.setflags()	|未实现（虚拟属性）

## 数据类型对象（dtype）

## 索引

In [290]:
a = np.arange(10).reshape(2, 5)
print(a)
print('*'*50)
ixgrid = np.ix_([0, 1], [2, 4])
print(ixgrid)
print('*'*50)
ixgrid[0].shape, ixgrid[1].shape 
#也就是说取0行和1行，拼接2列和4列 

[[0 1 2 3 4]
 [5 6 7 8 9]]
**************************************************
(array([[0],
       [1]]), array([[2, 4]]))
**************************************************


((2, 1), (1, 2))

* 迭代

In [291]:
a = np.arange(6).reshape(2,3)
it = np.nditer(a, flags=['f_index'])

In [292]:
while not it.finished:
...     print("%d <%d>" % (it[0], it.index), end=' ')
...     it.iternext()

0 <0> 1 <2> 2 <4> 3 <1> 4 <3> 5 <5> 

In [293]:
np.datetime64('2005-02', 'D')

numpy.datetime64('2005-02-01')

In [294]:
np.is_busday(np.datetime64('2011-07-15'))  # a Friday

True

In [295]:
np.busday_count(np.datetime64('2011-07-11'), np.datetime64('2011-07-18'))

5

ufunc.reduce(a[, axis, dtype, out, …])	减少一个接一个的尺寸，由沿一个轴施加ufunc。  
ufunc.accumulate(array[, axis, dtype, out])	累积将运算符应用于所有元素的结果。   
ufunc.reduceat(a, indices[, axis, dtype, out])	在单个轴上使用指定切片执行（局部）缩减。  
ufunc.outer(A, B, **kwargs)	将ufunc op应用于所有对（a，b），其中a中的a和b中的b。  
ufunc.at(a, indices[, b])	对'index'指定的元素在操作数'a'上执行无缓冲的就地操作。  