# 通用函数（ufunc，universal function）

* 通用函数是一种ndarrays以逐个元素操作的函数，支持数组广播，类型转换和其他一些标准功能。也就是说unfuc是一个函数的矢量化包装器，它接受固定数量的特定输入并产生固定数量的特定输出。  
* 在NumPy中，通用函数是numpy.func类的实例。许多内置函数都是在编译的C代码中实现的。基本的ufuncs对标量进行操作。单也有一种通用类型，基本元素是子数组（向量、矩阵等）。广播是在其他维度上完成的。也可以以ufunc使用frompyfunc工厂函数生成自定义示例。

## 广播

## 输出类型确定

In [2]:
import numpy as np

## 使用内部缓冲区

In [6]:
np.setbufsize(size=16)

8192

## 错误处理

In [9]:
old_settings = np.seterr(all='ignore')  #seterr to known value
np.seterr(over='raise')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

seterr([all, divide, over, under, invalid])	设置如何处理浮点错误。  
seterrcall(func)	设置浮点错误回调函数或日志对象。

## 映射规则

In [13]:
def print_table(ntypes):
... print( 'X'),
...     for char in ntypes: print char,
...     print
...     for row in ntypes:
...         print row,
...         for col in ntypes:
...             print int(np.can_cast(row, col)),
...         print
print_table(np.typecodes['All'])

IndentationError: expected an indented block (<ipython-input-13-7e1a3319d5c1>, line 2)

## 可选的关键字参数

* out  
    out关键字表示创建副本  
* where  
    True表示计算该位置的ufunc，值False表示仅将值保留在输出中。  
* axes  
    接受单个整数而不是元组，并且对所有输出都是标量的广义funcs。操作轴的索引的元组列表。  
    (i,j),(j,k)->(i,k)相应的axes关键字是[(-2,1),(-2,-1),(-2,-1)]  
* axis  
    轴维度：axes=[(axis,), (axis,), ()]  
* keepdims  
    True表示减小轴将作为持仓为1的持仓保留在结果中，以便结果将针对输入正确广播。
* casting  
    可能是'不'，'等于'，'安全'，'same_kind'或'不安全'。  
* order  
    指定输出数组的计算迭代顺序/内存布局。默认为“K”。'C'表示输出应该是C连续的，'F'表示F-连续，'A'表示F-连续，如果输入是F-连续的而且也不是C-连续的，否则是C-连续的，'K' '意味着尽可能地匹配输入的元素排序。  
* dtype  
* subok  
    True，如果是False，则输出将是严格数组，而不是子类型。
* signature  
    数据类型、数据类型的元组或指示ufunc的输入和输出类型的特殊签名字符串。 此参数允许您为1-d循环提供在基础计算中使用的特定签名。   
* extobj  
    长度为1、2或3的列表，指定ufunc缓冲区大小、错误模式整数和错误回调函数。 通常，这些值在特定于线程的字典中查找。

## 属性

|方法|描述|
|---|---|
|ufunc.nin	|输入数量。|
|ufunc.nout	|输出数量。|
|ufunc.nargs	|参数的数量。|
|ufunc.ntypes	|类型数量。|
|ufunc.types	|返回包含input-> output类型的列表。
|ufunc.identity	|身份价值。|
|ufunc.signature	|广义ufunc操作的核心元素的定义。|

## 方法  

In [18]:
# reduce 减少一个接一个的尺寸，由沿一个轴施加ufunc。
X = np.arange(8)
print(X)
print()
print(np.add.reduce(X,0))

[0 1 2 3 4 5 6 7]

28


In [19]:
# accumulate 累积将运算符应用于所有元素的结果。
np.add.accumulate([2, 3, 5])

array([ 2,  5, 10], dtype=int32)

In [20]:
# reduceat 在单个轴上使用指定切片执行（局部）缩减。
np.add.reduceat(np.arange(8),[0,4, 1,5, 2,6, 3,7])[::2]

array([ 6, 10, 14, 18], dtype=int32)

In [21]:
# outer  将ufunc op应用于所有对（a，b），其中a中的a和b中的b。
np.multiply.outer([1, 2, 3], [4, 5, 6])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [23]:
# at 对'index'指定的元素在操作数'a'上执行无缓冲的就地操作。
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1)
a

array([2, 3, 5, 4])